### ISSUE TITLE
下拉在mx4 pro上不正常，其他机型没测

### ISSUE THREAD

**Issue by start141** [guojunyi/PullDownListView#1]
![device-2015-03-10-123748](https://cloud.githubusercontent.com/assets/6055764/6569285/5bd9ac6c-c722-11e4-80f3-a6e9014191a3.png)
在mx4 pro上面运行下拉只能到图上的位置，无法继续下拉！

![device-2015-03-10-123812](https://cloud.githubusercontent.com/assets/6055764/6569292/9f609518-c722-11e4-8a25-9b41b1fd96e8.png)
松手之后是这样

**Comment by guojunyi** [comment]
@start141 已修改
